### ISSUE TITLE
[Bug] exception handling when input has less than or equal to one sentence

### ISSUE THREAD

**Issue by ayushsubedi** [ayushsubedi/term-article-summary#13]

**Comment by ayushsubedi** [comment]
```
Traceback (most recent call last):
  File "/Users/ayush/Desktop/personal/term-article-summary/env_test/bin/summarize", line 11, in <module>
    load_entry_point('summarize', 'console_scripts', 'summarize')()
  File "/Users/ayush/Desktop/personal/term-article-summary/env_test/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/ayush/Desktop/personal/term-article-summary/env_test/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/ayush/Desktop/personal/term-article-summary/env_test/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/ayush/Desktop/personal/term-article-summary/env_test/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/ayush/Desktop/personal/term-article-summary/summarize.py", line 93, in cli
    ratio=ratio))
  File "/Users/ayush/Desktop/personal/term-article-summary/summarize.py", line 52, in text_summary
    return summarize(text=text, ratio=ratio)
  File "/Users/ayush/Desktop/personal/term-article-summary/env_test/lib/python3.7/site-packages/gensim/summarization/summarizer.py", line 428, in summarize
    raise ValueError("input must have more than one sentence")
ValueError: input must have more than one sentence
```
